src/FrontendBundle/Entity/WebOrder.php
<?php

namespace FrontendBundle\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use DishBundle\Entity\Dish;
use RestaurantBundle\Entity\Shop;
use Symfony\Component\Validator\Constraints\DateTime;
use OrderBundle\Entity\Order;
use Doctrine\ORM\Mapping as ORM;

use Doctrine\ORM\Mapping\AttributeOverride;
use Doctrine\ORM\Mapping\AttributeOverrides;
use UserBundle\Entity\User;


/**
 * @ORM\Entity(repositoryClass="FrontendBundle\Entity\Repository\WebOrderRepository")
 * @ORM\Table()
 */
class WebOrder
{

    const TYPE_PICKUP = 0;
    const TYPE_DELIVERY = 1;

    const STATUS_FAIL = -2;
    const STATUS_CANCEL = -1;
    const STATUS_OPENED = 0;
    const STATUS_WAIT_FOR_KITCHEB = 1;
    const STATUS_WAIT_FOR_CLOSE = 3;
    const STATUS_CLOSED = 4;
    const STATUS_DELETED = 5;

    const STATUS_WAIT_FOR_MONEY = 10;
    const STATUS_PAID = 20;
    const STATUS_PAID_VERIFIED = 25;
    const STATUS_PRINTED = 30;
    const STATUS_READY = 40;

    const CASHTYPE_CASH = 0;
    const CASHTYPE_ONLINE = 1;
    const CASHTYPE_INVOICE = 2;
    const CASHTYPE_INTERNAL = 3;
    const CASHTYPE_CASH_CARD = 4;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity="FrontendBundle\Entity\WebOrderDish", mappedBy="order", cascade={"persist"})
     */
    private $dishes;

    /**
     * @ORM\ManyToOne(targetEntity="RestaurantBundle\Entity\PromoCard", inversedBy="orders")
     */
    private $promo;

    /**
     * @ORM\Column(name="status", type="integer", nullable=false)
     */
    private $status;

    /**
     * @ORM\Column(name="local_id", type="integer", nullable=false)
     */
    private $localId;

    /**
     * @ORM\Column(name="cash_type", type="smallint", nullable=true, options={"default" = 0})
     */
    private $cashType;

    /**
     * @ORM\Column(name="type", type="smallint")
     */
    private $type;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->status = Order::STATUS_OPENED;

    }

    /**
     * @ORM\ManyToOne(targetEntity="RestaurantBundle\Entity\Shop")
     */
    private $pickupShop;

    /**
     * @ORM\Column(name="pickup_time", type="string", nullable=true)
     */
    private $pickupTime;

    /**
     * @ORM\Column(name="phone", type="string", nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(name="address", type="string", nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(name="comment", type="text", length=300, nullable=true)
     */
    private $comment;



    /**
     * @return Shop
     */
    public function getPickupShop()
    {
        return $this->pickupShop;
    }

    /**
     * @param mixed $pickupShop
     * @return WebOrder
     */
    public function setPickupShop($pickupShop)
    {
        $this->pickupShop = $pickupShop;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPickupTime()
    {
        return $this->pickupTime;
    }

    /**
     * @param mixed $pickupTime
     * @return WebOrder
     */
    public function setPickupTime($pickupTime)
    {
        $this->pickupTime = $pickupTime;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * @param mixed $phone
     * @return WebOrder
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     * @return WebOrder
     */
    public function setAddress($address)
    {
        $this->address = $address;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param mixed $comment
     * @return WebOrder
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
        return $this;
    }


    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     * @return WebOrder
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return WebOrderDish[]
     */
    public function getDishes()
    {
        return $this->dishes;
    }

    /**
     * @param mixed $dishes
     * @return WebOrder
     */
    public function setDishes($dishes)
    {
        $this->dishes = $dishes;
        return $this;
    }

    /**
     * Add dish
     *
     * @param WebOrderDish $dish
     *
     * @return WebOrder
     */
    public function addDish(WebOrderDish $dish)
    {
        $this->dishes[] = $dish;
        $dish->setOrder($this);

        return $this;

    }

    /**
     * @return mixed
     */
    public function getPromo()
    {
        return $this->promo;
    }

    /**
     * @param mixed $promo
     * @return WebOrder
     */
    public function setPromo($promo)
    {
        $this->promo = $promo;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     * @return WebOrder
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLocalId()
    {
        return $this->localId;
    }

    /**
     * @param mixed $localId
     * @return WebOrder
     */
    public function setLocalId($localId)
    {
        $this->localId = $localId;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCashType()
    {
        return $this->cashType;
    }

    /**
     * @param mixed $cashType
     * @return WebOrder
     */
    public function setCashType($cashType)
    {
        $this->cashType = $cashType;
        return $this;
    }


    public function getFullSum()
    {
        $sum = 0;
        foreach ($this->dishes as $dish) {
            $sum += ($dish->getFullSum());
        }
        return $sum;
    }

    public function getDishSum()
    {
        $sum = 0;
        if ($this->dishes) {
            foreach ($this->dishes as $dish) {
                $sum += ($dish->getCashSum());
            }
        }
        return $sum;
    }

    public function getSumDiscount()
    {
        $sumDiscount = 0;
        foreach ($this->dishes as $dish) {
            $sumDiscount += ($dish->getDiscountSum());
        }
        return $sumDiscount;
    }


    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     * @return WebOrder
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

//ALTER TABLE web_order_dish DROP parent_dish_id, DROP parent_order_id, DROP delegate_id, DROP dish_id, DROP order_id

}

src/FrontendBundle/Entity/WebOrderDish.php
<?php

namespace FrontendBundle\Entity;

use DishBundle\Entity\Dish;
use Doctrine\ORM\Mapping as ORM;
use OrderBundle\Entity\Order;


/**
 * @ORM\Entity(repositoryClass="FrontendBundle\Entity\Repository\WebOrderDishRepository")
 * @ORM\Table()
 */
class WebOrderDish
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="FrontendBundle\Entity\WebOrder", inversedBy="dishes")
     */
    private $order;

    /**
     * @ORM\ManyToOne(targetEntity="DishBundle\Entity\Dish", cascade={"persist"})
     */
    private $dish;

    /**
     * @ORM\Column(name="quantity", type="float", nullable=false)
     */
    private $quantity;

    /**
     * @ORM\Column(name="dish_price", type="float", nullable=false)
     */
    private $dishPrice;

    /**
     * @ORM\Column(name="dish_discount", type="float", nullable=false)
     */
    private $dishDiscount;

    public function __construct(Order $order = null)
    {
        $this->order = $order;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * @param mixed $order
     */
    public function setOrder($order)
    {
        $this->order = $order;
    }

    /**
     * @return Dish
     */
    public function getDish()
    {
        return $this->dish;
    }

    /**
     * @param mixed $dish
     */
    public function setDish($dish)
    {
        $this->dish = $dish;
    }

    /**
     * @return mixed
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param mixed $quantity
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
    }

    /**
     * @return mixed
     */
    public function getDishPrice()
    {
        return $this->dishPrice;
    }

    /**
     * @param mixed $dishPrice
     */
    public function setDishPrice($dishPrice)
    {
        $this->dishPrice = $dishPrice;
    }

    /**
     * @return mixed
     */
    public function getDishDiscount()
    {
        return $this->dishDiscount;
    }

    /**
     * @param mixed $dishDiscount
     */
    public function setDishDiscount($dishDiscount)
    {
        $this->dishDiscount = $dishDiscount;
    }


    public function getCashSum()
    {
        return ($this->dishPrice * $this->quantity);
    }

    public function getDiscountSum()
    {
        return ($this->dishDiscount * $this->quantity);
    }

    public function getFullPrice()
    {
        return ($this->dishPrice + $this->dishDiscount);
    }

    public function getFullSum()
    {
        return ($this->getFullPrice() * $this->quantity);
    }
}

src/FrontendBundle/Entity/WebShopImage.php
<?php

namespace FrontendBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;


/**
 * @ORM\Entity()
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks
 */
class WebShopImage
{
    const TYPE_LOGO = 0;
    const TYPE_PREVIEW = 1;
    const TYPE_PANORAMA = 2;
    const TYPE_GALLERY = 3;
    const TYPE_GALLERY_MENU = 4;

    const IMAGE_TYPES = [
        self::TYPE_LOGO => 'Логотип',
        self::TYPE_PREVIEW => 'На главную',
        self::TYPE_PANORAMA => 'Панорама',
        self::TYPE_GALLERY => 'Галерея',
        self::TYPE_GALLERY_MENU => 'Меню',
    ];

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="FrontendBundle\Entity\WebShop", inversedBy="images")
     */
    private $shop;

    /**
     * @ORM\Column(type="text", name="image", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", name="title", nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text", name="description", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(name="type", type="smallint")
     */
    private $type;

    /**
     * @ORM\Column(name="is_deleted", type="boolean")
     */
    private $isDeleted;

    /**
     * @ORM\Column(name="created_at", type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="text", name="seo_alt", nullable=true)
     */
    private $seoAlt;


    public function __construct()
    {
        $this->type = self::TYPE_GALLERY;
        $this->isDeleted = false;
        $this->createdAt = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getShop()
    {
        return $this->shop;
    }

    /**
     * @param mixed $shop
     * @return WebShopImage
     */
    public function setShop($shop)
    {
        $this->shop = $shop;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     * @return WebShopImage
     */
    public function setImage($image)
    {
        $this->image = $image;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     * @return WebShopImage
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    public function getImagePath()
    {
        return $this->getImageUploadDir() . "/" . $this->image;
    }

    protected function getImageUploadDir()
    {
        return 'uploads/images/shop';
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     * @return WebShopImage
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     * @return WebShopImage
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }


    /**
     * @Assert\File(maxSize="60000000")
     */
    private $imageFile;

    private $temp;

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setImageFile(UploadedFile $file = null)
    {
        $this->imageFile = $file;
        // check if we have an old image path
        if (isset($this->image)) {
            // store the old name to delete after the update
            $this->temp = $this->image;
            $this->image = null;
        } else {
            $this->image = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getImageAbsolutePath()
    {
        return null === $this->image
            ? null
            : $this->getImageUploadRootDir() . '/' . $this->image;
    }

    protected function getImageUploadRootDir()
    {
        return __DIR__ . '/../../../web/' . $this->getImageUploadDir();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preImageUpload()
    {
        if (null !== $this->getImageFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->image = $filename . '.' . $this->getImageFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function uploadImage()
    {
        if (null === $this->getImageFile()) {
            return;
        }
        $this->getImageFile()->move($this->getImageUploadRootDir(), $this->image);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            //unlink($this->getImageUploadRootDir() . '/' . $this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->imageFile = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeImageUpload()
    {
        $file = $this->getImageAbsolutePath();
        if ($file) {
            //unlink($file);
        }
    }

    public function getTypeName($type) {
        return self::IMAGE_TYPES[$type];
    }

    /**
     * @return mixed
     */
    public function getisDeleted()
    {
        return $this->isDeleted;
    }

    /**
     * @param mixed $isDeleted
     * @return WebShopImage
     */
    public function setIsDeleted($isDeleted)
    {
        $this->isDeleted = $isDeleted;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param mixed $createdAt
     * @return WebShopImage
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getSeoAlt()
    {
        return $this->seoAlt;
    }

    /**
     * @param mixed $seoAlt
     * @return WebShopImage
     */
    public function setSeoAlt($seoAlt)
    {
        $this->seoAlt = $seoAlt;
        return $this;
    }


}

src/FrontendBundle/Resources/views/Cart/__cartShowTable.html.twig
<table id="order-table">
    <thead>
    <tr>
        <th class="item-thumb">Блюдо</th>
        <th class="item-desc">Описание</th>
        <th>Цена</th>
        <th class="item-count">Количество</th>
        <th>Итого</th>
        <th class="remove-item"></th>
    </tr>
    </thead>
    <tbody>
    {% for dish in order.dishes %}
        <tr data-id="{{ dish.dish.id }}" class="cart-item-row">
            <td class="item-thumb">
                <figure>
                    <img src="{{ dish.dish.imagePath | imagine_filter('cart') }}" alt="{{ dish.dish.name }}">
                </figure>
            </td>
            <td class="item-desc">
                <p>{{ dish.dish.name }}</p>
                <p style="font-size: 12px;" class="description">{{ dish.dish.description }}</p>
            </td>
            <td><strong>{{ dish.dish.shopPrice(0) | price }} р</strong></td>
            <td>
                <input data-id="{{ dish.dish.id }}" data-price="{{ dish.dishPrice }}" data-category="{{ dish.dish.category.id }}"
                       type="text" class="cart-item-count {% if dish.dish.id != 13242 %}stepper{% endif %}" name="quantity"
                       value="{{ dish.quantity }}">
            </td>
            <td><strong class="sum">{{ (dish.quantity * dish.dish.shopPrice(0)) | price }}</strong> р</td>
            <td class="remove-item">
                {% if dish.dish.id != 13242 %}
                    <a href="#" class="remove-items-link"><i class="fa fa-times-circle"></i></a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div style="display: none" id="orderSum">{{ orderSum }}</div>

src/FrontendBundle/Resources/views/Cart/cartCheckout.html.twig
{% extends '@Frontend/base_v3.html.twig' %}

{% block page_special_styles %}
    {% stylesheets
        "css/new/bootstrap.min.css"
        "css/new/bootstrap_col_15.css"
        "css/new/fontello.css"
        "css/new/owl.carousel.css"
        "css/new/magnific-popup.css"
        "css/new/custom-bg.css"

        "css/new/reset.css"
        "css/new/main.css"
        "css/new/main_new.css"

        filter="scssphp" %}
        <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css"/>
    <style>
        .owl-carousel .owl-item img {
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block container -%}
    <section class="store-cart style2">
        <div class="container">
            <h1>{{ 'Ваш заказ' | trans }} </h1>
            <table class="order-table">
                {% for orderDish in order.dishes %}
                    <tr style="border-bottom: 1px #000 solid">
                        <td>{{ orderDish.dish.name }}</td>
                        <td>{{ orderDish.quantity }}</td>
                        <td>{{ orderDish.cashSum | price }} р.</td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2"><b>{{ 'Итого' | trans }}:</b></td>
                    <td><strong style="font-weight: bold;color: #000;">{{ order.dishSum | price }} р.</strong></td>
                </tr>
                <tr>
                    <td><b>{{ 'Телефон'  | trans }}:</b></td>
                    <td>{{ order.phone }}</td>
                </tr>
                {#<tr>#}
                {#<td><b>{{ 'Адрес'  | trans }}:</b></td>#}
                {#<td>{{ order.address }}</td>#}
                {#</tr>#}
                <tr>
                    <td><b>{{ 'Дополнительно'  | trans }}:</b></td>
                    <td>
                        <p>{{ order.comment }}</p>
                        <p>
                            {% if promoCard is defined and promoCard is not null %}
                                {% if promoCard.id == 2 %}
                                    Скидка за онлайн оплату 15%
                                {% else %}
                                    Скидка держателю карты {{ promoCard.cardDiscount }}%
                                {% endif %}
                            {% endif %}
                        </p>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        {% if order.cashType == constant('OrderBundle\\Entity\\Order::CASHTYPE_ONLINE') %}
                            <p> Вы будете переадресованы на защищенную платежную страницу системы ArtPay.</p>
                            <p> На платежной странице будет отображаться номер заказа в интернет магазине, наименование товара(ов) и сумма заказа.
                                Введите реквизиты банковской карточки - номер, имя на карте, срок действия, CVV2/CVC2 код и адрес электронной почты
                                для получения электронного карт-чека и кликните «Оплатить».</p>
                            <p> Передача данных в процессе оплаты заказа происходит в защищенном режиме с использованием технологий 3-D Secure
                                Verified by VISA и MasterCard Secure Code.</p>
                            <p> В результате проведенной оплаты с использованием банковской платежной карты будет сформирован карт-чек в электронном
                                виде, отражающий реквизиты операции оплаты и являющийся подтверждением совершения операции оплаты и в котором отражены
                                реквизиты операции оплаты, который необходимо сохранять до момента получения товар/услуги. </p>
                        {% else %}
                            <p style="color:#f00;">Мы отправили код подтверждения на номер <strong>{{ order.phone }}</strong></p>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="3" style="padding: 0;">
                        <a href="{{ path("frontend_cart_show") }}" class="custom-button">{{ 'В корзину' | trans }}</a>

                        {% if app.session.get("order_type") == constant('FrontendBundle\\Entity\\WebOrder::TYPE_PICKUP') %}
                            <a href="{{ path("frontend_takeaway_menu") }}" class="custom-button">{{ 'Отменить' | trans }}</a>
                        {% else %}
                            <a href="{{ path("frontend_delivery_menu") }}" class="custom-button">{{ 'Отменить' | trans }}</a>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="3" style="padding: 0;">
                        {% if order.cashType == constant('OrderBundle\\Entity\\Order::CASHTYPE_ONLINE') %}
                            <form action="{{ payment.gate }}" method="POST">
                                {% for key, data in transaction %}
                                    <input type="hidden" name="{{ key }}" value="{{ data }}">
                                {% endfor %}
                                <button class="custom-button" type="submit" style="width: 100%;">{{ 'Перейти к оплате' | trans }}</button>
                            </form>
                        {% else %}
                            <form method="POST" class="cart-confirmation" action="{{ path('frontend_cart_confirmation') }}">
                                <input required type="text" name="code"
                                       style="font-size: 26px;    border: #f00 2px solid;    margin: 10px 15px 10px 0;    width: 100%;    display: block;    padding: 10px;    max-width: initial;"
                                       placeholder="{{ 'Код подтверждения' | trans }}">
                                <button class="custom-button" type="submit" style="margin: 10px 0;">{{ 'Подтвердить' | trans }}</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="clearfix"></div>
    </section>
{% endblock %}


    {% block page_special_javascripts %}


        {% javascripts
            "js/new/jquery.min.js"
            "js/new/jquery-ui.min.js"
            "js/new/jquery.scrollme.min.js"
            "js/new/jquery.fs.stepper.min.js"
            "js/new/cd-google-map-brown.js"
            "js/new/jquery.mixitup.min.js"
            "js/new/wow.min.js"
            "js/new/plugins.js"
            "js/new/main.js"

            filter="?jsqueeze" %}

            <script src="{{ asset_url }}"></script>

        {% endjavascripts %}

        <script type="text/javascript">
            $(document).ready(function () {
                $("#order_phone").val(localStorage.phone);
                $("#order_address").val(localStorage.address);
            });
            $(".cart-confirmation").on("submit", function (event) {
                event.preventDefault();
                let code = $(this).find('input[name="code"]').val();
                $.ajax({
                    url: "{{ path('frontend_cart_confirmation') }}",
                    type: "POST",
                    data: {code},
                    statusCode: {
                        200: function (xhr) {
                            location.href = "/cart/success";
                        },
                        403: function (xhr) {
                            alert('Неверный код подтверждения');
                        }
                    }
                });

                return false;
            });
        </script>
    {% endblock %}

src/FrontendBundle/Resources/views/Cart/cartInline.html.twig
<div class="shopping-cart style2">
    <div class="cart-container clearfix">
        <a href="#" class="cart-link"><span>{{ (order is defined and order is not null) ? order.dishes | length : 0 }}</span></a>
        <div class="cart-items">
            <div class="cart-counter">
                <h5><span><span>{{ (order is defined and order is not null) ? order.dishes | length : 0 }}</span> позиций</span> в корзине</h5>
            </div>
            <ul>
                {% if order is defined and order is not null %}
                    {% for dish in order.dishes %}
                        <li>
                            <div class="item-container clearfix" data-id="{{ dish.dish.id }}">
                                <a href="#" class="remove-items"><i class="fa fa-times-circle"></i></a>

                                <figure>
                                    <img src="{{ dish.dish.imagePath | imagine_filter('cart') }}">
                                </figure>
                                <p class="food-name">
                                    <a href="{{ path('frontend_show_dish', {'name' : dish.dish.name}) }}">{{ dish.dish.name }}</a>
                                </p>

                                <p class="food-price">{{ dish.quantity }}&times;{{ dish.dish.shopPrice(0) | price }}р</p>
                            </div>
                        </li>
                    {% endfor %}
                {% endif %}
                <li class="order_price">
                    {#<div class="item-container clearfix">Итого: <span class="order_summary">{{ cart['summary'] }} руб.</span></div>#}
                </li>
            </ul>
            <a href="{{ path('frontend_cart_show') }}" class="button view-cart-btn">Корзина</a>
            {#<a href="{{ path('frontend_checkout') }}" class="button checkout-btn">Оформить</a>#}

            <a href="{{ path('frontend_cart_show') }}" class="button checkout-btn">Оформить</a>

            <div class="checkout button view-cart-btn" style="margin-top: 10px; width: 260px;">
                {#{{ dump(order.dishes) }}#}
                <span class="order_summary">{{ orderSum }} р</span>
            </div>
        </div>
    </div>
</div>