src/RestaurantBundle/Entity/PromoCard.php
<?php

namespace RestaurantBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use OrderBundle\Entity\Order;
use UserBundle\Entity\ClientCredentials;
use UserBundle\Entity\User;

/**
 * @ORM\Table(name="promo_cards")
 * @ORM\Entity(repositoryClass="RestaurantBundle\Entity\Repository\PromoCardRepository")
 */
class PromoCard
{

    const TYPE_MANUAL = 0;
    const TYPE_CARD = 1;
    const TYPE_TOURIST = 2;

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="card_id", type="string", unique=true, length=8)
     */
    private $cardId;

    /**
     * @ORM\Column(name="local_id", type="string", length=8, nullable=true)
     */
    private $localId;

    /**
     * @ORM\Column(name="card_discount", type="integer")
     */
    private $cardDiscount;

    /**
     * @ORM\OneToOne(targetEntity="UserBundle\Entity\ClientCredentials", inversedBy="card")
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity="OrderBundle\Entity\Order", mappedBy="promo")
     */
    private $orders;

    /**
     * @ORM\Column(name="qr_code", type="string", unique=true, length=8)
     */
    private $qrCode;

    /**
     * @ORM\Column(name="card_sum", type="float", nullable=true)
     */
    private $cardSum;

    /**
     * @ORM\Column(name="is_active", type="boolean", nullable=true, options={"default": "0"})
     */
    private $isActive;

    /**
     * @ORM\Column(name="is_visible", type="boolean", nullable=true, options={"default": "0"})
     */
    private $isVisible;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User")
     */
    private $createdBy;

    /**
     * @ORM\Column(name="issued_at", type="datetime", nullable=true)
     */
    private $issuedAt;

    /**
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User")
     */
    private $issuedBy;

    /**
     * @ORM\Column(name="type", type="smallint")
     */
    private $type;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->isVisible = false;
        $this->isActive = false;
        $this->type = self::TYPE_CARD;
        $this->cardDiscount = 5;
        $this->cardSum = 0;
    }

    /**
     * Add order
     *
     * @param \OrderBundle\Entity\Order $order
     *
     * @return PromoCard
     */
    public function addOrder(\OrderBundle\Entity\Order $order)
    {
        $this->orders[] = $order;

        return $this;
    }

    /**
     * Remove order
     *
     * @param \OrderBundle\Entity\Order $order
     */
    public function removeOrder(\OrderBundle\Entity\Order $order)
    {
        $this->orders->removeElement($order);
    }

    /**
     * Get orders
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * Set cardId
     *
     * @param string $cardId
     *
     * @return PromoCard
     */
    public function setCardId($cardId)
    {
        $this->cardId = $cardId;

        return $this;
    }

    /**
     * Get cardId
     *
     * @return string
     */
    public function getCardId()
    {
        return $this->cardId;
    }

    /**
     * Set phone
     *
     * @param string $phone
     *
     * @return PromoCard
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set cardDiscount
     *
     * @param integer $cardDiscount
     *
     * @return PromoCard
     */
    public function setCardDiscount($cardDiscount)
    {
        $this->cardDiscount = $cardDiscount;

        return $this;
    }

    /**
     * Get cardDiscount
     *
     * @return integer
     */
    public function getCardDiscount()
    {

        return $this->cardDiscount;
    }

    /**
     * Set isVisible
     *
     * @param boolean $isVisible
     *
     * @return PromoCard
     */
    public function setIsVisible($isVisible)
    {
        $this->isVisible = $isVisible;

        return $this;
    }

    /**
     * Get isVisible
     *
     * @return boolean
     */
    public function getIsVisible()
    {
        return $this->isVisible;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return PromoCard
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set type
     *
     * @param integer $type
     *
     * @return PromoCard
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }


    /**
     * @return User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * @param User $createdBy
     */
    public function setCreatedBy($createdBy)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     *
     * @return PromoCard
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }


    /**
     * @return mixed
     */
    public function getQrCode()
    {
        return $this->qrCode;
    }

    /**
     * @param mixed $qrCode
     * @return PromoCard
     */
    public function setQrCode($qrCode)
    {
        $this->qrCode = $qrCode;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param mixed $isActive
     * @return PromoCard
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
        return $this;
    }

    /**
     * @return ClientCredentials
     */
    public function getClient()
    {
        return $this->client;
    }

    /**
     * @param mixed $client
     * @return PromoCard
     */
    public function setClient($client)
    {
        $this->client = $client;
        return $this;
    }

    /**
     * @return float
     */
    public function getOrderSum()
    {
        $sum = 0;
        $hasPromo = false;
        if ($this->getClient()) {
            $promoOrder = $this->getClient()->getPromoOrder();

            foreach ($this->getOrders() as $__order) {
//                if ($promoOrder->getId() == $__order->getId()) $hasPromo = true;
                $sum += $__order->getFullSum();
            }

/*            if ($this->getClient()->getPromoOrder())
                if (!$hasPromo)
                    $sum += $this->getClient()->getPromoOrder()->getFullSum();*/
        }
        return $sum;
    }

    /**
     * @return float
     */
    public function getFullSum()
    {
        return $this->getOrderSum() + $this->cardSum;
    }


    /**
     * @return Order
     */
    public function getLastOrder()
    {
        if (count($this->orders) > 0) {
            return $this->orders->first();
        } else {
            return $this->getClient()->getPromoOrder();
        }
    }


    /**
     * @return float
     */
    public function getCardSum()
    {
        return $this->cardSum;
    }

    public function addCardSum($sum)
    {
        $this->cardSum += $sum;
        return $this;
    }

    /**
     * @param mixed $cardSum
     * @return PromoCard
     */
    public function setCardSum($cardSum)
    {
        $this->cardSum = $cardSum;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getLocalId()
    {
        return $this->localId;
    }

    /**
     * @param mixed $localId
     * @return PromoCard
     */
    public function setLocalId($localId)
    {
        $this->localId = $localId;
        return $this;
    }


    /**
     * @return \DateTime
     */
    public function getIssuedAt()
    {
        return $this->issuedAt;
    }

    /**
     * @param mixed $issuedAt
     * @return PromoCard
     */
    public function setIssuedAt($issuedAt)
    {
        $this->issuedAt = $issuedAt;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getIssuedBy()
    {
        return $this->issuedBy;
    }

    /**
     * @param mixed $issuedBy
     * @return PromoCard
     */
    public function setIssuedBy($issuedBy)
    {
        $this->issuedBy = $issuedBy;
        return $this;
    }

    public function getMostVisitedShop($return = 'name')
    {
        $shops = [];
        foreach ($this->getOrders() as $order) {
            @$shops[$order->getShop()->getName()] += 1;
        }
        arsort($shops);
        return count($shops) > 0 ? ($return == 'name' ? key($shops) : $shops[key($shops)]) : "";
    }

}

src/RestaurantBundle/Controller/CustomController.php
<?php

namespace RestaurantBundle\Controller;

use RestaurantBundle\Entity\Client;
use RestaurantBundle\Entity\Shop;
use RestaurantBundle\Form\Type\ClientType;
use RestaurantBundle\Service\KEscPos;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use TerminalBundle\Entity\DailyReport;
use UserBundle\Entity\UserEvent;

/**
 * @Route("/admin")
 */
class CustomController extends Controller
{
    /**
     * @Route("/test", name="test_printer")
     */
    public function testAction(Request $request)
    {

        $escpos = new KEscPos('TM-T88IV AFU', "pizza", true, true);
        $escpos->UseTranslation(false);

//        $escpos->Font("A");
//        $escpos->Align("center");
//        $escpos->Height('double');
//        $escpos->Double(true);
        $line = "";
//        for ($i = 1024; $i <= 2048; $i++) {
//            $line .= $i . chr($i) . "-";
//        }
        $escpos->Line('tratrattatatrtar тратратратар');
        $escpos->Line('tratrattatatrtar');
        $escpos->Line('тратратратар');
//        $escpos->Line($line);
        $escpos->XFeed();
        $escpos->XFeed();
        $escpos->XFeed();
        $escpos->XFeed();
        $escpos->XFeed();
//        $escpos->Cut();
        $escpos->Close();
        dump($escpos);
        dump(123);
        die();
    }


    /**
     * @Route("/client/list", name="client_list")
     */
    public function clientsListAction(Request $request)
    {
        $clients = $this->getDoctrine()->getRepository("RestaurantBundle:Client")->findAll();
        $client = new Client();

        $form = $this->createForm(ClientType::class, $client, [
            'action' => $this->generateUrl("client_create")
        ]);

        return $this->render("@Restaurant/Custom/clientsList.html.twig", [
            'form' => $form->createView(),
            'form_title' => 'Новый клиент',
            'clients' => $clients,
        ]);
    }

    /**
     * @Route("/client/add", name="client_create")
     */
    public function clientCreateAction(Request $request)
    {
        $client = new Client();

        $form = $this->createForm(ClientType::class, $client, [
            'action' => $this->generateUrl("client_create")
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($client);
                $em->flush();

                return $this->redirectToRoute("client_list");
            }
        }
    }

    /**
     * @Route("/client/{id}/edit", name="client_edit")
     */
    public function clientEditAction(Request $request, Client $client)
    {
        if (!$client) {
            die("error");
        }
        $clients = $this->getDoctrine()->getRepository("RestaurantBundle:Client")->findAll();

        $form = $this->createForm(ClientType::class, $client, [
            'action' => $this->generateUrl("client_edit", [
                'id' => $client->getId()
            ])
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($client);
                $em->flush();

                return $this->redirectToRoute("client_edit", [
                    'id' => $client->getId()
                ]);
            }
        }

        $orders = $this->getDoctrine()->getRepository('OrderBundle:Order')->findByClient($client);

        return $this->render("@Restaurant/Custom/clientsList.html.twig", [
            'form' => $form->createView(),
            'clients' => $clients,
            'orders' => $orders,
            'form_title' => 'Редактирование клиента'
        ]);
    }

    /**
     * @param Request $request
     * @Route("/export/shop/{id}/manual/{report}", name="manual_export_command")
     */
    public function exportManualAction(Request $request, Shop $shop, DailyReport $report)
    {
        $report = $this->getDoctrine()->getRepository('TerminalBundle:DailyReport')->find($report);

        $kernel = $this->get('kernel');
        $application = new Application($kernel);
        $application->setAutoExit(false);

        $input = new ArrayInput(array(
            'command' => 'restaurant:report:export',
            '--report' => $report
        ));

        $output = new BufferedOutput();
        $application->run($input, $output);

        $content = $output->fetch();

        return new JsonResponse($content);
    }


}

src/RestaurantBundle/Resources/views/Custom/clientsList.html.twig
{% extends "RestaurantBundle::layout.html.twig" %}

{% block title %}
    {{ 'Клиенты' | trans }}
{% endblock %}

{% form_theme form '@Restaurant/Form/Fields.twig' %}

{% block container %}
    <div id="page_content_inner">
        <div class="uk-grid">
            <div class="uk-width-medium-1-2">
                <div class="md-card">
                    <div class="md-card-content">
                        <h3 class="heading_a uk-margin-bottom">{{ 'Клиенты' | trans }}</h3>

                        <div class="uk-overflow-container">
                            <table class="uk-table uk-table-nowrap" id="client_list">
                                <thead>
                                <tr>
                                    <th class="uk-width-2-10">Название</th>
                                    <th class="uk-width-2-10">УНП</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for client in clients %}
                                    <tr>
                                        <td class="uk-text-left">
                                            <a href="{{ path("client_edit", { 'id' : client.id }) }}">{{ client.name }}</a>
                                        </td>
                                        <td class="uk-text-left">
                                            {{ client.unp }}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="uk-form-row">
                            <a href="{{ path("client_list") }}" class="md-btn md-btn-primary">Добавить</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="uk-width-medium-1-2">
                <div class="md-card">
                    <div class="md-card-content">
                        <h3 class="heading_a uk-margin-bottom">{{ form_title }}</h3>
                        {{ form_start(form) }}

                        {{ form_row(form.name) }}
                        {{ form_row(form.unp) }}

                        <div class="" style="padding: 15px 0;">
                            {{ form_widget(form.isExportable) }}
                        </div>

                        <div class="" style="padding: 15px 0;">
                            {{ form_widget(form.trackInDelivery) }}
                        </div>

                        <div class="" style="padding: 15px 0;">
                            {{ form_widget(form.isDeleted) }}
                        </div>

                        <div class="md-input-wrapper">
                            {{ form_row(form.submit) }}
                        </div>

                        {{ form_end(form) }}
                    </div>
                </div>

                {% if orders is defined %}
                    <div class="md-card">
                        <div class="md-card-content">
                            <h3 class="heading_a uk-margin-bottom">{{ 'Счета' | trans }}</h3>
                            <table class="uk-table uk-table-nowrap">
                                <thead>
                                <tr>
                                    <th>{{ "Номер счета" | trans }}</th>
                                    <th>{{ "Заведение" | trans }}</th>
                                    <th>{{ "Дата" | trans }}</th>
                                    <th>{{ "Официант" | trans }}</th>
                                    <th>{{ "Сумма" | trans }}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                    <tr>
                                        <td>
                                            <a href="{{ path('admin_order_show', {'id' : order.id}) }}">
                                                {{ order.localId }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ path('admin_order_show', {'id' : order.id}) }}">
                                                {{ order.shop.name }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ path('admin_order_show', {'id' : order.id}) }}">
                                                {{ order.createdAt | date('d.m.Y H:i') }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ path('user_edit', {'id' : order.user.id}) }}">
                                                {{ order.user.name }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ path('admin_order_show', {'id' : order.id}) }}">
                                                {{ order.fullSum | price }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}


    {% block page_specific_plugins %}

        <!-- datatables -->
        <script src="/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>
        <!-- datatables colVis-->
        <script src="/bower_components/datatables-colvis/js/dataTables.colVis.js"></script>
        <!-- datatables tableTools-->
        <script src="/bower_components/datatables-tabletools/js/dataTables.tableTools.js"></script>
        <!-- datatables custom integration -->
        <script src="/assets/js/custom/datatables_uikit.min.js"></script>

        <script>
            $("table").DataTable({
                iDisplayLength: -1,
            });
        </script>


    {% endblock %}

src/RestaurantBundle/Resources/views/Custom/delegate.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<dish>
    <place id="{{ shop.id }}" name="{{ shop.alias }}" date="{{ date | date("d-m-Y") }}" total_summ="{{ total }}">
        {% for dish in dishes %}
            {% if (dish.dish.id >= 20000) and (dish.dish.id <= 30000) and (dish.dish.category.id == 82) %}
                {% set dishId = dish.dish.id - 10000 %}
            {% else %}
                {% set dishId = dish.dish.id %}
            {% endif %}
            <dish id="{{ dishId }}" count="{{ dish.quantity }}" summ="{{ (dish.quantity * dish.dishPrice) }}" doze="1" price="{{ dish.dishPrice }}" zakaz_type="2" client="{{ dish.order.client is null ? delegateTo.exportAlias : dish.order.clientName }}" name="{{ dish.dish.name }}" fullprice="{{ (dish.dish.shopPrice(shop.id)) }}"/>
        {% endfor %}
    </place>
</dish>

src/RestaurantBundle/Resources/views/Custom/export.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<dish>
    <place id="{{ shop.id }}" name="{{ shop.alias }}" date="{{ date | date("d-m-Y") }}" total_summ="{{ total }}" cash="{{ totalA['cash'] }}" card="{{ totalA['terminal'] }}" kitchen="{{ totalA['КУХНЯ'] }}" bar="{{ totalA['БАР'] }}">
        {% for dish in dishes %}
            {% if (dish.dish.id >= 20000) and (dish.dish.id <= 30000) and (dish.dish.category.id == 82) %}
                {% set dishId = dish.dish.id - 10000 %}
            {% else %}
                {% set dishId = dish.dish.id %}
            {% endif %}
            
            <dish id="{{ dishId }}" count="{{ dish.quantity }}" summ="{{ (dish.quantity * dish.dishPrice) }}" doze="1" price="{{ dish.dishPrice }}" zakaz_type="{{ dish.order.cashType }}" client="{{ dish.order.clientName }}" name="{{ dish.dish.name }}" fullprice="{{ (dish.fullPrice) }}"/>
        {% endfor %}
    </place>
</dish>

src/RestaurantBundle/Resources/views/Custom/export2.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<dish>
    <place id="{{ shop.id }}" name="{{ shop.alias }}" date="{{ date | date("d-m-Y") }}" total_summ="{{ total }}" cash="{{ totalA['cash'] }}" card="{{ totalA['terminal'] }}" kitchen="{{ totalA['КУХНЯ'] }}" bar="{{ totalA['БАР'] }}">
        {% for dish in dishes %}
            {% if (dish.dish.id >= 20000) and (dish.dish.id <= 30000) and (dish.dish.category.id == 82) %}
                {% set dishId = dish.dish.id - 10000 %}
            {% else %}
                {% set dishId = dish.dish.id %}
            {% endif %}
            
            <dish id="{{ dishId }}" count="{{ dish.quantity }}" summ="{{ (dish.quantity * (dish.dishPrice - dish.dishDiscount)) }}" doze="1" price="{{ dish.dishPrice-dish.dishDiscount }}" zakaz_type="{{ dish.order.cashType }}" client="{{ dish.order.clientName }}" name="{{ dish.dish.name }}" fullprice="{{ (dish.fullPrice) }}"/>
        {% endfor %}
    </place>
</dish>

src/RestaurantBundle/Resources/views/Custom/marcoReport.csv.twig
{#DATE;BIG;SMALL;TOTAL;BIG;SMALL;TOTAL;BIG;SMALL;TOTAL;BIG;SMALL;TOTAL;BAR;CUCINA;PIZZA;ICECREAM;SUSHI;P.MEDIO;DESSERT;TOTAL#}
{% for id, report in data %}
    {{- report.date | date('Y-m-d')  ~ ';' -}}
    {{- report.big.new  ~ ';' -}}
    {{- report.small.new ~ ';' -}}
    {{- (report.big.new + (report.small.new / 2)) | number_format(2, ',', '')  ~ ';' -}}

    {{- report.big.waste  ~ ';' -}}
    {{- report.small.waste  ~ ';' -}}
    {{- (report.big.waste + (report.small.waste / 2)) | number_format(2, ',', '')  ~ ';' -}}

    {{- report.big.used  ~ ';' -}}
    {{- report.small.used  ~ ';' -}}
    {{- (report.big.used + (report.small.used / 2)) | number_format(2, ',', '')  ~ ';' -}}

    {{- report.big.balance  ~ ';' -}}
    {{- report.small.balance  ~ ';' -}}
    {{- (report.big.balance + (report.small.balance / 2)) | number_format(2, ',', '')  ~ ';' -}}

    {{- report.cash.bar | number_format(2, ',', '') ~ ';' -}}
    {{- report.cash.kitchen | number_format(2, ',', '')  ~ ';' -}}
    {{- report.cash.pizza | number_format(2, ',', '')  ~ ';' -}}
    {{- report.cash.icecream | number_format(2, ',', '')  ~ ';' -}}
    {{- report.cash.sushi | number_format(2, ',', '')  ~ ';' -}}

    {% if (report.big.used + (report.small.used / 2)) > 0 %}
        {{- (report.cash.pizza / (report.big.used + (report.small.used / 2))) | number_format(2, ',', '')  ~ ';' -}}
    {% else %}
        {{- 0  ~ ';' -}}
    {% endif %}

    {{- report.cash.desert | number_format(2, ',', '')  ~ ';' -}}

    {{- report.cash.total | number_format(2, ',', '') }}
{% endfor %}

src/RestaurantBundle/Resources/views/Custom/marcoReportDelivery.csv.twig
{#                shop      #}
{#DATE;BIG;SMALL;TOTAL;TOTAL#}
{{- date | date('Y-m-d')  ~ ';' -}}
{% for shop, __data in data %}
    {{- (__data.ingr['Шарик большой'] + __data.ingr['Шарик малый'] / 2) ~ ';' -}}
    {{- __data.sum ~ ';' -}}
{% endfor %}

src/RestaurantBundle/Resources/views/Custom/pizzaPhotoMail.html.twig
<p>Pizza photo validation</p>

<p>There are <strong>{{ toValidation | length }}</strong> photos to be validated</p>

<p>
    <a href="https://admin.venezia.by/admin/photolist">GO TO VALIDATION</a>
</p>

src/RestaurantBundle/Resources/views/Custom/pizzaPhotoMailMonthly.html.twig
<html>
<body>
<h1>Pizza photo monthly validation stats</h1>

<h2>User stats</h2>
<table>
    <thead>
    <tr>
        <th>Waiter</th>
        <th>Photo checks</th>
    </tr>
    </thead>
    <tbody>
    {% set __sum = 0 %}
    {% for __user in userData %}
        <tr>
            <td>{{ __user.name }}</td>
            <td>{{ __user.uCount }}</td>
        </tr>
        {% set __sum = __sum + __user.uCount %}
    {% endfor %}
    <tr>
        <td><b>SUM</b></td>
        <td>{{ __sum }}</td>
    </tr>
    </tbody>
</table>

<h2>Validation stats</h2>
<table>
    <thead>
    <tr>
        <th>Validator</th>
        <th>Photo checks</th>
    </tr>
    </thead>
    <tbody>
    {% set __sum = 0 %}
    {% for __user in validationData %}
        <tr>
            <td>{{ __user.name }}</td>
            <td>{{ __user.uCount }}</td>
        </tr>
        {% set __sum = __sum + __user.uCount %}
    {% endfor %}
    <tr>
        <td><b>SUM</b></td>
        <td>{{ __sum }}</td>
    </tr>
    </tbody>
</table>


<h2>Shop stats</h2>
<table>
    <thead>
    <tr>
        <th>Shop</th>
        <th>Pizza baked</th>
        <th>Average time, min</th>
        <th>Min time, min</th>
        <th>Max time, min</th>
    </tr>
    </thead>
    <tbody>
    {% set __sum = 0 %}
    {% for __shop in photoData %}
        <tr>
            <td>{{ __shop.name }}</td>
            <td>{{ __shop.pCount }}</td>
            <td>{{ (__shop.avgTime / 60) | price }}</td>
            <td>{{ (__shop.minTime / 60) | price }}</td>
            <td>{{ (__shop.maxTime / 60) | price }}</td>
        </tr>
        {% set __sum = __sum + __shop.pCount %}
    {% endfor %}
    <tr>
        <td><b>SUM</b></td>
        <td>{{ __sum }}</td>
    </tr>
    </tbody>
</table>


<h2>AI stats</h2>
<table>
    <thead>
    <tr>
        <th>Pizza</th>
        <th>Count</th>
        <th>Valid</th>
        <th>Percent</th>
    </tr>
    </thead>
    <tbody>

    {% for __pizza, stats in aiStats %}
        <tr>
            <td>{{ __pizza }}</td>
            <td>{{ stats.count }}</td>
            <td>{{ stats.aiValid }}</td>
            <td>{{ (stats.percent) | price }}%</td>
        </tr>
    {% endfor %}
    <tr>
        <td><b>OVERALL</b></td>
        <td>{{ aiRate.count }}</td>
        <td>{{ aiRate.aiValid }}</td>
        <td>{{ aiRate.percent | price }}%</td>
    </tr>
    </tbody>
</table>


</body>
</html>